title: "Esteemed.io"
description: >-
url: "https://esteemed.io"
email: service@esteemed.io
meta:
  image: "img/esteemed-main-meta.png"
google_analytics: UA-167435008-1

# Build settings
markdown: kramdown
plugins:
  - jekyll-menus

collections:
  authors:
    title: Authors
    output: true
  categories:
    title: Categories
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title/
  -
    scope:
      path: ''
      type: authors
    values:
      permalink: "/blogs/author/:title/"
      layout: authors
  -
    scope:
      path: ''
      type: categories
    values:
      permalink: "/blogs/category/:title/"
      layout: categories
