title: "Esteemed.io"
description: >-
url: "https://esteemed.io"
email: service@esteemed.io
meta:
  image: "img/esteemed-main-meta.png"
google_analytics: UA-167435008-1

# Build settings
markdown: kramdown
plugins:
  - jekyll-menus
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title/
